apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  annotations:
    configmap.reloader.stakater.com/reload: "console-config"
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: joamps/app:latest
          ports:
            - containerPort: 5050 
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret