apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: registry.digitalocean.com/kidfriendlysocial/app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050 
          resources:
            requests:
              cpu: "32m"
              memory: "512Mi"
            limits:
              cpu: "32m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret     