apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  labels:
    app: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: ml-model
        model: distilroberta
    spec:
      containers:
        - name: ml-model
          resources:
          image: joamps/ml-model:latest
          ports:
            - containerPort: 3000 