apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.12.1
          args:
            - "--collect.global_status"
            - "--collect.engine_innodb_status"
            - "--collect.info_schema.processlist"
            - "--web.listen-address=:9104"
            - "--web.telemetry-path=/metrics"
          env:
            - name: DATA_SOURCE_NAME
              value: "user:password@(mysql-service:3306)/"
          ports:
            - containerPort: 9104
