apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysql-exporter:25060']
